### ISSUE TITLE
Clarification about the HorizontalDivider Component

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#100]
@MaksymTaratuta55 
@kirti75waytech 

What does the `HorizontalDivider` component look like and where do we use it?

I am talking about this component:  https://github.com/ramsayinnovations/ramsay-site/blob/develop/src/components/elements/HorizontalDivider.jsx

**Comment by MaksymTaratuta55** [comment]
It seems it is this line in the middle:
<img width="738" alt="Screenshot 2020-12-29 at 12 32 42" src="https://user-images.githubusercontent.com/29330551/103277574-09203e80-49d2-11eb-8161-c43f78ec7b1b.png">

It has been used before, so I just create a separate component for it.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Great - thanks
