### ISSUE TITLE
Naming Convention for Images

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#101]
Let's use a BEM type system for image names in the `develop--clone` branch.  As such, please make the following changes both in the `public/img` folder and where ever those images are being used:

* `call-to-action-left-pattern.svg` --> `pattern__cta--left.svg`
* `contact-us-left-side-pattern.svg` --> `pattern__contact--left.svg`
* `call-to-action-right-pattern-sm.svg` --> `pattern__cta--right-sm.svg`
* `call-to-action-right-pattern.svg` --> `pattern__cta--right.svg`
* `contact-us-right-side-pattern.svg` --> `pattern__contact--right.svg`

**Comment by kirti75waytech** [comment]
@thecodeclimber @MaksymTaratuta55 I have resolved this issue and created its PR #122. I have renamed all the images as per BEM style given above. Please review it and let me if any modifications required.
Thanks
