### ISSUE TITLE
Move the form folder

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#103]
Please move the `components/form` folder to `components/elements/form` in the `develop--clone` branch.  After all, the `InputTextForm`, `SelectForm` & `TextareaForm` components are simply `element` components.

That is, unless you are @MaksymTaratuta55 think this is a bad idea (if so, please let me know why).

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, @thecodeclimber, I think the better way is to leave it how it is now.
My logic is:
- we have form components: input, textarea, select, etc... So these components should be in the folder 'form'.
- And as it is a form components folder 'form' should be in the folder "components".
- Components that do not belong to anything could be in the folder './components/elements'
- Layout components should be in the folder './components/layout/....'

@thecodeclimber what do you think about it?

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 
@kirti75waytech 

Okay, we will keep it as it is for now.  If need be, we can revisit the issue in the future.
