### ISSUE TITLE
Rename Form Element Components

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#104]
In the `develop--clone` branch please rename the [form components](https://github.com/ramsayinnovations/ramsay-site/tree/develop/src/components/form) as follows:

* InputTextForm --> Input
* SelectForm --> Select
* TextareaForm --> TextArea

Please rename the file to match the new component name (i.e., `Input.jsx`, `Select.jsx`, `TextArea.jsx`)

**Note:** If you already moved the form components, then they should now be located here  https://github.com/ramsayinnovations/ramsay-site/tree/develop/src/components/elements/form

**Comment by kirti75waytech** [comment]
@thecodeclimber @MaksymTaratuta55 I have renamed the form component and their respective imports used in the project. Please review the PR #130 for this issue and let me know if any other modification is needed.
Thanks
