### ISSUE TITLE
Create Button Component

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#112]
I would like to create a `Button` component within the `components/elements` folder in the `develop--clone` branch.

The `Button` component should be based off of the tailwind ui buttons:  https://tailwindui.com/components/application-ui/elements/buttons

We currently have four buttons on the site:

### 1
![image](https://user-images.githubusercontent.com/65869221/103284593-51485c80-49e4-11eb-93b6-dc6cb7168269.png)

### 2 and 3
![image](https://user-images.githubusercontent.com/65869221/103284616-5c02f180-49e4-11eb-9e6f-ddb7d9c17590.png)

### 4
![image](https://user-images.githubusercontent.com/65869221/103284635-6a510d80-49e4-11eb-93e0-f38fe608de51.png)

There are three noticeable properties:

* 2 different shapes (pill and slightly rounded)
* Two different colors
* Two different paddings (compare button 1 to buttons 2 and 3)

The button component should be able to handle all the different properties by adding `tailwind-css` classes.

Please let me know if you have any questions, comments or suggestions.

Thanks.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

What is the point of `isCustomDisplay`?  I.e., when would we use it and when would we not use it?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber it is for changing default display class to inline, flex, etc
