### ISSUE TITLE
Update New Header Compontents

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#129]
Update the new Header components to look like the design in the current, live site:  https://ramsayinnovations.com/

# Current

![image](https://user-images.githubusercontent.com/65869221/103378764-221d1280-4aec-11eb-88be-fd0035191737.png)

* Logo too small
* Need to add container padding
* Font Size & font weight of menu items

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Please take a look at branch `issue/#129--update-new-header-component` that I just created:  https://github.com/ramsayinnovations/ramsay-site/tree/issue/%23129--update-new-header-component

In particular, at the following:

* https://github.com/ramsayinnovations/ramsay-site/tree/issue/%23129--update-new-header-component/src/components/elements/navbar

* https://github.com/ramsayinnovations/ramsay-site/tree/issue/%23129--update-new-header-component/src/components/layouts/main/header

What I am trying to do is create reusable navbar components that we will then use in the header.  That way, we can use them not just in this particular header -- but in future projects down the road.  Or, in other words, I am trying to make a UI library out of the Tailwind UI components.

As you can see, though, it is not finished.  Here are some items that still need work:

* Creating a NavLink component
* Making the Mobile navbar component more reusable (see below)
* Creating constants for the logo props (more on that below)

## Mobile Navbar

I would like to break the Mobile navbar component into sub-components. I am not sure how to best do it -- but right now I see there being two or three main sections.  One the Header section where the Logo and Close button are located.  Two, the content area (where the links are located).  And (perhaps) three the footer (where the Button is located).

Can you please try and implement this?  Thanks.

## Logo Constants

I would like to add the prop data for the Logo component in the `Header.constant.js` file.  I would like to divide it into the "base" data and the "mobile" data.  For example:

* base:
  * url to logo image
  * href (where the logo links to)
  * width
  * height
  * alt text
* mobile
  * width
  * height

The point is that the `mobile` data will only include that data which overrides the base data (so if we wanted to use a different logo image we could.  on the other hand, if we want to use the same image -- we would just use the base version.

Could you implemenet this?

Thanks.

**Comment by MaksymTaratuta55** [comment]
Blocked by #137

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

eslint is giving me a number of errors.  Can you please fix them?  Thanks.

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, could you please give me a screen? I haven't any errors

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Can we close this?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I think yes

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 -- shall do, thanks.
