### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by kirti75waytech** [ramsayinnovations/ramsay-site#133]
@thecodeclimber @MaksymTaratuta55 I have completed all the tickets assigned to me. Please assign me more task for the next week.
Thanks

**Comment by kirti75waytech** [comment]
@thecodeclimber @MaksymTaratuta55  I created the PR for the issues assigned to me last week. Please, review them and let me know if any changes are required. If all looks I request you to merge them. And please assign new tasks for this week. Thanks

**Comment by thecodeclimber** [comment]
@kirti75waytech 

Thanks -- I will assign more tasks as soon as I can.

**Comment by kirti75waytech** [comment]
> @kirti75waytech
> 
> Thanks -- I will assign more tasks as soon as I can.

@thecodeclimber Thanks
