### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#136]
1. We should add "ramsay-project" to each task to automatically adding it to the project dashboard. 
<img width="428" alt="Screenshot 2021-01-04 at 13 48 01" src="https://user-images.githubusercontent.com/29330551/103532204-7e3cb980-4e93-11eb-97e7-a57f0f6c4c9c.png">

2. We should add "Closes #IssueNumber" (example `Closes #12`) in the description of each pull request to automatically close the issue. Other info should be added below in new comments.
<img width="985" alt="Screenshot 2021-01-04 at 13 50 49" src="https://user-images.githubusercontent.com/29330551/103532532-12a71c00-4e94-11eb-8187-3c88d6144d19.png">

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Let's create a `develop--clone` project and then use the `develop--clone` label as you described above.  In other words, I would like to break this up into sub-projects -- and the first sub project I want to work on is getting the `develop--clone` finished.

Thanks.

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, but what will be when we merge develop--clone into develop and then into master?

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

The goal is to REPLACE the `develop` branch with the `develop--clone` branch once we have finished the `develop--clone` branch.
