### ISSUE TITLE
hookform/resolvers/yup bug

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#137]
I have found out a bug with @hookform/resolvers/yup. I delete `.next`, `node_modules` folders, and yarn.lock file, then I run `yarn` to install packages, and then I received this message.
<img width="893" alt="Screenshot 2021-01-06 at 00 15 30" src="https://user-images.githubusercontent.com/29330551/103706041-ca334f80-4fb4-11eb-8a79-765a1088296f.png">

I repeat it in the develop--clone branch and received the same result.
@thecodeclimber, @kirti75waytech, could you please check it too in the new test branch? It seems there are some problems with the package

**Comment by kirti75waytech** [comment]
Okay @MaksymTaratuta55 Let me check.

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, @thecodeclimber, I've solved the problem. It was with `"@hookform/resolvers": "1.3.2",` package.  To fix it I installed `"@hookform/resolvers": "1.3.0",`

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 Have you updated the `develop--clone` branch?

**Comment by kirti75waytech** [comment]
> @kirti75waytech, @thecodeclimber, I've solved the problem. It was with `"@hookform/resolvers": "1.3.2",` package. To fix it I installed `"@hookform/resolvers": "1.3.0",`

@MaksymTaratuta55 Have you updated the `develop--clone` branch?
