### ISSUE TITLE
Create Video component

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#143]
Create a common Video component with `div` wrapper and props: `src`, `controls`, `autoplay`, etc. Video is paused by default and able to be paused at any moment.

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 Do I need to complete this ticket?

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, sorry I haven't had tasks and noticed that you didn't change the status, so I took it for myself. But You can start #144 if you want. But you shouldn't implement Typography and Video components, just wait for merges for them

**Comment by kirti75waytech** [comment]
> @kirti75waytech, sorry I haven't had tasks and noticed that you didn't change the status, so I took it for myself. But You can start #144 if you want. But you shouldn't implement Typography and Video components, just wait for merges for them

Okay @MaksymTaratuta55 I will do #144 issue, when #142 and #143 will be merged.

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, you can start to refactor the layout now and after merges put needed components into the right places in your layout

**Comment by kirti75waytech** [comment]
Okay @MaksymTaratuta55, sure.
