### ISSUE TITLE
Get Contact Form Integrated & Working

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#18]
Hi there,

I just want to centralize back and forth about the contact form here in Github.  Last I heard there is a 302 error.  Please update where we are holding in terms of the contact form being integrated into Active Campaign.

Thanks,

Moshe

**Comment by kirti75waytech** [comment]
@thecodeclimber Still getting 302 error from backend api when I submit the form. I think this needs to be look from backend. Let me know if I need to do anything else from my end?
