### ISSUE TITLE
Add Required Field Asterisk to Form Fields

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#22]
Please watch the following video  https://www.loom.com/share/41cbddae25bc4b7abfb9a8525dc1f836

# Tasks

* Add required field asterisk to all form fields in the call-to-acton form field above the footer.

**Comment by thecodeclimber** [comment]
Please note -- I have changed the color of the asterisk to grey-500.  We will use a red color ONLY in the error state (as will be discussed in a future issue).

**Comment by kirti75waytech** [comment]
This one is also completed. Please review and let me know in case of any other changes are required. Thanks

**Comment by thecodeclimber** [comment]
Please have the asterisk be 4px from the top and right.

**Comment by kirti75waytech** [comment]
This should be fixed now. Can you please check and let me know in case of any other changes are required. Thanks @thecodeclimber
