### ISSUE TITLE
Contact Form Action

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#28]
For now, please have the contact form send an email to info@ramsayinnovations.com.  We will work on the integration to Active Campaign at a later date.

**Comment by kirti75waytech** [comment]
@thecodeclimber How can I send email as we are not using any backend server in this project so far? Can you please provide some more insight on this?

**Comment by thecodeclimber** [comment]
Let's use FormSpree and the formspree cli (I have already signed up for an account)

* **Website URL: **  https://formspree.io/  
* **CLI Documentation: ** https://help.formspree.io/hc/en-us/articles/360053819114
* **Video Tutorial: **  https://www.youtube.com/watch?v=31COiWAmZso

I added your email to our formspree account.  You should receive an email asking you to validate your email address.  Once validated, you can access the relevant keys on the Ramsay Contact Form project.

Please let me know if you have any questions.

**Comment by thecodeclimber** [comment]
p.s. please check your spam folder if you don't see the verification email from formspree.

**Comment by thecodeclimber** [comment]
P.S. 2 -- for now we'll just send the form to info@ramsayinnovations.com (like I mentioned above).
