### ISSUE TITLE
Redo Hero Section

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#3]
https://www.loom.com/share/c129c4c7829046b8821deeb7ac6dd99c

**Comment by thecodeclimber** [comment]
NOTE:  I will have to get the curved design later on.

**Comment by thecodeclimber** [comment]
Here is the video of how to add the curve:  https://www.loom.com/share/e2293f05ab8d41959c426435e9083ce2 
i also sent you a comment about it via figma

**Comment by kirti75waytech** [comment]
This is almost done today (Left side background fixed, right side background getting some issue), please verify and let me know if any other change required.

**Comment by thecodeclimber** [comment]
Can you let me know what issues?  

Also, there are some other issues that we need to deal with.  Here is a video showing them:

https://www.loom.com/share/ec7af329c1994758a6fbe3f0a1e1e010

**Comment by lokesh75way** [comment]
I did a lot research but could not find the way how to arrange three different layers in Redo Hero Section
Layers are line-images, curve-image and vector-character-images.
Because line-images are below the vector-character-images and concurrently line-images are placed above the curve-image.
Please share your thoughts or advise on this.

**Comment by thecodeclimber** [comment]
Hi there,

I’m happy to share my thoughts (I’ll just have to do a little research first).  With that said, isn’t this a job for kirti?  Did I accidently send you the work request?

Be well,

Moshe

**Comment by kirti75waytech** [comment]
@thecodeclimber Yes it was assigned to me and I have added the following comment but yesterday Lokesh logged in his github account to my pc to verify something and he forgot to logout. Then I mistakenly sent my comments from his github acocunt. Didn't realise that I was writing from his account. Anyway, thanks for noticing this and getting it into my consideration.

**Comment by thecodeclimber** [comment]
No worries about the account :).

In terms of the background image -- I have created a branch called moshe-branch.  I have made a number of changes which I will make a video on and explain (probably on Sunday).  Until then, be well.

**Comment by kirti75waytech** [comment]
Sure, also please assign me more task for next week as I don't have any open ticket. @thecodeclimber

**Comment by thecodeclimber** [comment]
Hi there,

Please take a look at this video and make the necessary changes:  https://www.loom.com/share/3760dc93a08c4c74848fe53fe02627b0

if you have questions, thoughts or comments -- please don't hesitate to ask and/or share.

**Comment by thecodeclimber** [comment]
P.S.  I still have to look into the mobile version.

**Comment by thecodeclimber** [comment]
P.S. 2  In the video I made a mistake.  When I noticed that the hero section worked on different mobile sizes -- that was YOUR work I was looking at (not mine).  Well done :).  Nonetheless, I would still like to make the changes mentioned in the above video and again to avoid using negative margins as much as possible.  You can, of course, use negative left or negative right with position.  That's not a problem -- it's just negative margins that can cause problems.

**Comment by kirti75waytech** [comment]
This one is also completed. Please review and let me know in case of any other changes are required. Thanks
