### ISSUE TITLE
Send Emails to Right Email Address

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#32]
All emails from the contact us form need to go to the following email address:  info@ramsayinnovations.com

You should have backend access to formspree.  If you don't, please let me know and I'll get you access.

Also - dowe need to set up environmental variables on our hosting?

**Comment by kirti75waytech** [comment]
Changed the email address to info@ramsayinnovations.com. Please check it, let me know if any changes are required. Thanks
