### ISSUE TITLE
Fix Curve on Home Page

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#33]
The curves between sections on the home page don't look good on large screen sizes.  please fix.  thanks.

**Comment by kirti75waytech** [comment]
Fixed the curves between sections on home page for all screen sizes. Please check it. Thanks

**Comment by thecodeclimber** [comment]
@morrisjon Jon -- please take a look and confirm that it looks good on your screen.

**Comment by morrisjon** [comment]
This is resolved now
