### ISSUE TITLE
Fix Blurry Logo on Mobile

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#36]
The logo is blurry on mobile devices.  Please fix.

here is a screenshot:

![image](https://user-images.githubusercontent.com/65869221/102555638-d459e080-40cf-11eb-9f40-0eaa5ff14472.png)

**Comment by kirti75waytech** [comment]
Fixed the blurry Logo for mobile view. Please check it. Thanks

**Comment by thecodeclimber** [comment]
@kirti75waytech Why are you using a .png version of the logo for the mobile view.  The desktop version is a .svg file -- and can scale up or down without losing quality.  Please fix.

**Comment by kirti75waytech** [comment]
@thecodeclimber Because the SVG logo looks like blurry when I export it. So that's the reason why I export the .PNG logo because it looks much clear than SVG. Can you please take a look on the mobile SVG logo file if that seems good to you? I think this is only issue with the logo image.

Please advise.

**Comment by thecodeclimber** [comment]
Please switch to the .svg version and please ask @MaksymTaratuta55 for suggestions on how to get it to look clear.  Thanks.

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 When I am using .svg file, It gets blurry in mobile devices. Please suggest me to deal with it.

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, you use a .png image on mobile devices `"/img/main-logo-sm.png"`. Please change the image for mobile or use one SVG for all window sizes.
**/header/index.js**
```
 <div>
              <img src="/img/main-logo.svg" alt="Logo" onClick={() => router.push('/')} className="object-contain cursor-pointer w-32 px-2 sm:w-40 lg:w-auto md:px-0 hidden md:block" />
              <img src="/img/main-logo-sm.png" alt="Logo" onClick={() => router.push('/')} className="object-contain cursor-pointer px-2 sm:w-40 lg:w-auto md:px-0 md:hidden" />
            </div>
```

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 For your reference, I am sharing the screenshot of my earlier code from my last commit, where I have used a single .svg file for all the devices. But I was facing the blurry logo issue at that time too.
But If you want me to change the code again. So, I will do it too. Please let me know If I also need to push the code.
Thanks

![Screenshot 2020-12-24 at 10 59 50 PM](https://user-images.githubusercontent.com/74037279/103087641-45ebde80-463c-11eb-96b7-54de2a06f6d2.png)

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, in your's third <img> you use `main-logo-sm.png`, and it looks blurry. So you should use SVG instead because SVG scales correctly

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 It seems there was some misunderstanding, What I tried to say, I coded in this way earlier:
`<img src="/img/main-logo.svg" alt="Logo" onClick={() => router.push('/')} className="object-contain cursor-pointer w-32 px-2 sm:w-40 lg:w-auto md:px-0" />`
which you are suggesting me, but it is also creating the blurry logo. I have created a branch for this issue: `issue/#36--fix-blurry-logo-on-mobile` and pushed my code on it.Kindly, look my code and test it. 
Please, let me know the required changes.

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, ok, thx. I'll check

**Comment by MaksymTaratuta55** [comment]
<img width="447" alt="Screenshot 2020-12-24 at 15 30 27" src="https://user-images.githubusercontent.com/29330551/103091496-04880e80-45fd-11eb-96d5-db42ffca19e1.png">
@kirti75waytech, it seems everything ok now

**Comment by kirti75waytech** [comment]
Hi @MaksymTaratuta55, Yes, It also looks good to me. So, I am creating its PR.

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, I don't see PR, could you please check?

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 here is the PR #73 for this issue. Sorry for the delay.

**Comment by thecodeclimber** [comment]
@kirti75waytech 
@MaksymTaratuta55 

I am closing this issue and continuing the conversation on PR #78
