### ISSUE TITLE
Curve Flattens on Mobile View

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#37]
Please take a look at the bottom right corner of the curve. It flattens out.  

![image](https://user-images.githubusercontent.com/65869221/102555868-55b17300-40d0-11eb-9dc2-9b6c9c8c9796.png)

Please fix - thanks.

**Comment by kirti75waytech** [comment]
Fixed the Flatten curve on the mobile view. Please check it. Thanks

**Comment by thecodeclimber** [comment]
@morrisjon Please check on mobile version and make sure that it looks okay.  Please let us know here on github whether or not it is fixed.  Thanks.

**Comment by morrisjon** [comment]
This is resolved.
