### ISSUE TITLE
Title & Description Text Changes on Mobile

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#38]
Please make sure that the Title and Desription on the mobile version has the same text as on the desktop version.

For example:

THE RAMSAY METHOD

Desktop:

![image](https://user-images.githubusercontent.com/65869221/102555997-93160080-40d0-11eb-833e-953c6b779bd3.png)

Mobile:

![image](https://user-images.githubusercontent.com/65869221/102556476-a8d7f580-40d1-11eb-9bb8-559759242af6.png)

Notice that the description text changes on mobile.  It should be the same text as the desktop version.

The same happens for the The Ramsay Advisor & The Ramsay Commitment sections. 

Please update the text on all three sections so that they are the same Title and Description text as the desktop version.

Thanks,

Moshe

**Comment by kirti75waytech** [comment]
Deleted all the mobile and tablet Titles and Descriptions and updated them as same as the desktop's Titles and Descriptions . Please review and let me know in case of any other changes are required. Thanks
