### ISSUE TITLE
Create git workflow

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#39]
Git workflow should be:
1. "main" branch for production.
2. "develop" branch for development
3. Each issue should have its own branch from "develop" and merged to "develop" after the finish. Issue branch should naming: #{issue number}-{task-title}

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 Are you suggesting that we use the following system:  https://www.youtube.com/watch?v=1SXpE08hvGs

Also, when you say that "each issue should have its own branch" -- do you mean an issue like this one that I am commenting on right now (Create git workflow #39?)?  Or do you mean each feature.

@kirti75waytech I would like to start implementing a git workflow as per Max's comment above.  As such, we should do the following:

* Create a Development branch
* Start creating feature branches for the different elements of the site that we are working on using the naming convention that Max suggested:  i.e., #{feature namber}-{task-title}.

If you have any questions about how to do this -- please post them here.  Thanks.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 I am going to assign this issue to you so that you can oversee that we are implementing it properly.

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, okay. Yes, almost like this https://www.youtube.com/watch?v=1SXpE08hvGs except for the release branch.
Issue branch name example:
**39-create-git-workflow**

**Comment by MaksymTaratuta55** [comment]
> Also, when you say that "each issue should have its own branch" -- do you mean an issue like this one that I am commenting on right now (Create git workflow #39?)? Or do you mean each feature.

@thecodeclimber, I mean each issue that needs to be implemented in code, a developer should create an issue branch (example 39-create-git-workflow) from "develop" branch, then implement it in this brach and then merge it back to the "develop" brach

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I have added "develop" branch

**Comment by kirti75waytech** [comment]
@thecodeclimber created the "40-refactoring-folder-structure" branch from "develop" branch. As per the git flow I have pushed my code on the "40-refactoring-folder-structure" branch for your review. This branch consist of same kind of issue as you have suggested me to create a common branch for that. The issues which I have fixed under this branch are : 39, 40, 42, 45, 49, 50, 56, 57, 58, 59. Please, let me know If any changes are required. Thanks

@MaksymTaratuta55 Please let me know, If I need to merge this "40-refactoring-folder-structure" branch into "develop" branch, after review. Or If any changes are required. Thanks

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, I think you can create a pull request into "develop" branch for review. And if you pass the review, @thecodeclimber can confirm it, and it will merge it automatically. (if you select "delete the branch after the merge, it will delete it automatically too).
Also, you can add a comment with links to issues that were solved in this PR. For example just type: #40

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech , @thecodeclimber, also, I added an 'In progress' label and advice to use it for more comfort 🙂

**Comment by thecodeclimber** [comment]
Just for reference, I am going to list here as links the issues that `40-refactoring-folder-structure` addresses:

* #39
* #40
* #42
* #45
* #49
* #50
* #56
* #57
* #58
* #59

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 -- if I understand correctly, Kirti should create a separate branch for each of the issues above. For example, the 40 branch should be this: `#40--add-src-folder`.  42 could be `#42--base-to-app`.  And so on.

Is that correct?

Also, I think I would prefer a double dash after the number -- i.e., `#40--add-src-folder` as opposed to `#40-add-src-folder`.  I just think it's easier to read.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 -- another question.  When do we close an issue.  When it is pushed to the main branch?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, sure we can use double dash `--`, if you want.

>  if I understand correctly, Kirti should create a separate branch for each of the issues above. For example, the 40 branch should be this: #40--add-src-folder. 42 could be #42--base-to-app. And so on.
>
>Is that correct?
Yes, you are right. But in this case, we can leave it as it is already done.

**Comment by MaksymTaratuta55** [comment]
>  When do we close an issue. When it is pushed to the main branch?

I think we can add the label 'Done' and put it to issues that have been done. And close the issue when we merge it to the master branch. But developers should look after that.

**Comment by thecodeclimber** [comment]
@kirti75waytech -- two changes for the future when creating new branches:

1. Each issue should be its own branch.  
For example, in the branch `40-refactoring-folder-structure` -- you included issues 39, 40, 42, 45, etc.  We should NOT do it that way.  Rather, 39 should be it's own branch, 40 a different branch, 42 yet another branch, etc.

1. Use a double dash `--` after the number.  For example, `#40--refactoring-folder-structure`.  NOT `#40-refactoring-folder-structure`.

Thanks.

@MaksymTaratuta55 -- agreed about keeping it in this case.  Also -- I have created a `Done` label.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 -- is there a process for testing and quality assurance?

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 -- I would like to suggest a slight modification to this system:

### Overall Structure

Here is a list of the different type of branches:

* `main` -- for production
* `develop` -- for development
* `release` -- for stable release versions
* `hotfix` -- to patch a production release
* `feature` -- for new features
* `issue` -- for branches related to issues

The `feature` branches will be new features that we introduce.  They will have the following naming structure

* feature/{feature name}
* example: `feature/blog__posts--sidebar`

Note, btw, the BEM naming convention.

The `issue` branches will be branches that are created in response to issues created in the Issues section of github.  They will have the following naming structure:

* issue/#{issue number}--{issue name}

Example: `issue/#139--fix-blog-sidebar-search`

---

What are your thoughts?

**Comment by kirti75waytech** [comment]
@thecodeclimber I have created the single branch `40-refactoring-folder-structure` as you have suggested in the issue: #56. 
Those issues were having similar tasks. So I created a single branch for them. But from now I will create separate branches for each issue, and follow the above structure as you have mentioned here.

**Comment by kirti75waytech** [comment]
@thecodeclimber and @MaksymTaratuta55 For your information. I am creating new branches for the other issues from `40-refactoring-folder-structure` as only this branch has the latest code. As soon It gets merge to the `develop` branch, I will start creating the new issue branches from the `develop` branch.
Please let me know, If I required to do anything else.
Thanks

**Comment by MaksymTaratuta55** [comment]
https://github.com/ramsayinnovations/ramsay-site/issues/39#issuecomment-750693826

@thecodeclimber, sorry, I think it will bring some complications and I think the better way is just to add these labels for issues or create some desk like trello. I think it is better to hold only 2 stable branches (main and develop) and we won't update every branch (issue, feature release and etc.) on every commit to the develop branch.

**Comment by kirti75waytech** [comment]
Yes I agree with @MaksymTaratuta55 we should hold only 2 branches : 
- main : for Production
- develop : for Development

rest of the branches will be based on `feature/#12--xyz-task-details` and `issue/#13--issue-details`

Please confirm if we are on the same page?
cc @thecodeclimber 
Thanks

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, @kirti75waytech could you please clarify why we should use "feature", "issue",... in a branch name too?

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 I believe It could be better to distinguish between an `issue` which I mean a fix required in existing code while `feature` I meant a new code implementation. If it doesn't look necessary to keep `feature` and `issue` branches then we can follow the structure  which you have suggested earlier.

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 We have now `develop` branch with the latest code. But I see there are some code which are not properly merged. 
For Example: `HeaderNavBar.jsx` has `Header.constant.js` code while the same code is already present in the `Header.constant.js`. We need to fix it before we create any other branches from `develop` branch. Please create an Issue for this, So we can work on this fix.

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, yes there were some problems with rebase yesterday, and since the code was not written by me, I couldn't do it more properly. I think I fixed these problems in my PR #72. Could you please check it?

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 I have reviewed the PR #72. It's looking good to me.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 
@kirti75waytech 

Thanks for all of your work on this.  I have accepted the PR #72 merge request.

In terms of `feature` and `issue`.  I also think it makes sense to differentiate between new features and fixing issues/problems. 
 However, I am fine with whatever you two think we should do.
 
Please let me know what you decide and then we can close this issue :).

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 
@kirti75waytech 

I'm going to close this issue.  If you think there is anything to add, please feel free to add it here and I can re-open it.

**Comment by MaksymTaratuta55** [comment]
+
