### ISSUE TITLE
Add './src' folder

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#40]
Add './src' folder to the root. It should contain "pages", "component", "utils"

**Comment by thecodeclimber** [comment]
@kirti75waytech Please take a look at Max's comment above about creating an `.src` folder.  Please note, it should NOT include the `public` folder.  When all is said and done, this should be the file structure:

ROOT
- .vscode
- src
  -- styles
    -- tailwind.css
  -- components
  -- pages
  -- utils
- public
  -- img
.gitignore
README.md
formspree.json
...
yarn.lock

NOTE;  I **changed** `assets/css/index.css` to `styles/tailwind.css`.  Please note that change -- particularly when importing styles.

NOTE 2:  Please update `jsconfig.json` after creating the `src` folder and renaming the `assets` folder.

NOTE 3:  Remove `"@/graphql...` from the `jsconfig.json` file.

**Comment by kirti75waytech** [comment]
@thecodeclimber Changed the assets/css/index.css to styles/tailwind.css and removed the "@/graphql... from the jsconfig.json file and updated the "@/assets/*": ["assets/*"] to "@/styles/*": ["styles/*"].
Please, let me know If any changes are required.
Thanks

**Comment by thecodeclimber** [comment]
@kirti75waytech 

We still need to fix the `jsconfig.json` file.  Here is the current code:

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/styles/*": ["styles/*"],
      "@/components/*": ["components/*"],
      "@/public/*": ["public/*"]
    }
  }
}
```

But that won't work -- `styles` and `components` are in the `src` folder now.  We need something like this:

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/styles/*": ["src/styles/*"],
      "@/components/*": ["src/components/*"],
      "@/public/*": ["public/*"]
    }
  }
}
```

We should also add `utils` and pages to the `paths`.  So it should look like this:

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/components/*": ["src/components/*"],
      "@/pages/*": ["src/pages/*"],
      "@/public/*": ["public/*"],
      "@/styles/*": ["src/styles/*"],
      "@/utils/*": ["src/utils/*"],     
    }
  }
}
```

Finally ,we should REMOVE `public` from the list.  So the final list should look like this:

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/components/*": ["src/components/*"],
      "@/pages/*": ["src/pages/*"],
      "@/styles/*": ["src/styles/*"],
      "@/utils/*": ["src/utils/*"],     
    }
  }
}
```

Now, when we import a file from one of these folders, we can do so like this:

`import ContactUs from "@/components/content/contact-us";`

**Comment by kirti75waytech** [comment]
@thecodeclimber **Noted**

**Comment by kirti75waytech** [comment]
Hi! @MaksymTaratuta55  and @thecodeclimber, I have created the MR [https://github.com/ramsayinnovations/ramsay-site/pull/66]#66 for this issue. Please review it and let me know If any changes are required.
Thanks

**Comment by kirti75waytech** [comment]
Hi! @MaksymTaratuta55 and @thecodeclimber, I have created the MR #66 for this issue. Please review it and let me know If any changes are required.
Thanks
