### ISSUE TITLE
Rename component files

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#41]
All files are ".js" but components must be ".jsx" and started with an uppercase character.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Is the same true for files created under the `pages` or `utils` directories?  I.e.,:

* should they also have a `.jsx` extension?
* should they also start with an uppercase character?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, only react components (pages are react components too) must be with `.jsx` extension.
If it is just a file with common functions (for example in the utils folder) they must be just with `.js` extension.

**Comment by kirti75waytech** [comment]
@thecodeclimber Changes have been done. Please review this and let me know If changes are required. Thanks

**Comment by thecodeclimber** [comment]
Thanks.
