### ISSUE TITLE
"base.js" must be in "_app.js".

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#42]
"./components/layouts/base.js" must be in the "_app.js".
And different <title> could be described on every page in the <head>

**Comment by thecodeclimber** [comment]
@kirti75waytech Please note Max's comment above.  I made a short video showing how I believe this should be done:  https://www.loom.com/share/8f635e7838f34c838f1ce0a2ea33699b

Thanks.

**Comment by kirti75waytech** [comment]
@thecodeclimber Changes have been done. Please review this and let me know If changes are required. Thanks

**Comment by thecodeclimber** [comment]
@kirti75waytech & @MaksymTaratuta55 -- I added a `review` label.  My recommendation is that after an issue has been coded that we should add the `review` label (and remove the `in progress` label) and reassign the issue to whowever needs to review it.  Please let me know if you agree.  Thanks.

**Comment by MaksymTaratuta55** [comment]
Sure. I also recommend making all merges with a pull request. It will be more comfortable for reviewers and it auto closes the merged branch. 
@thecodeclimber, what do you think?

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 -- sounds fine to me.  Can I ask, though, what is the alternative to handling merges with a pull request?

**Comment by kirti75waytech** [comment]
@thecodeclimber Yes, It's good to have a review label.

**Comment by MaksymTaratuta55** [comment]
> @MaksymTaratuta55 -- sounds fine to me. Can I ask, though, what is the alternative to handling merges with a pull request?

I think just make reviews manually 🙂
