### ISSUE TITLE
Use Prettier

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#44]
Add Prettier to the project for having a common code style.
Add Prettier to package.json, add config, add the Prettier extension to VSCode, and set formating on saving property.

**Comment by thecodeclimber** [comment]
A few questions:

* Should we also use eslint?
* Any suggested settings or style guides for either:
  * prettier
  * eslint

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I think eslint is not required, but if you want you can use it.
Prettier example:
```{
  "tabWidth": 2,
  "singleQuote": true,
  "trailingComma": "all",
  "printWidth": 120
}
```
ESLint example:
```
{
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "rules": {
        "semi": "error"
    }
}
```

**Comment by thecodeclimber** [comment]
@kirti75waytech -- please add prettier with the configuration as detailed by Max above.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

What do you think about using one of the following:  

* Standard.js:  https://standardjs.com/
* eslint-config-get-off-my-lawn with prettier: https://www.npmjs.com/package/eslint-config-get-off-my-lawn
* elsint-config-airbnb with prettier: https://www.npmjs.com/package/eslint-config-airbnb

The first one (standard) is a set it and forget it option.  The third option (airbnb) seems to be the most popular.  The middle option seems to be rather comprehensive.

Your thoughts?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I've already installed eslint with this config:
```
{
  "env": {
    "browser": true,
    "es2021": true
  },
  "extends": ["eslint:recommended", "plugin:react/recommended"],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "plugins": ["react"],
  "rules": {
    "react/react-in-jsx-scope": "off"
  }
}
```
But I don't mind if you want to use airbnb elsint config
