### ISSUE TITLE
Less mess components in code

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#47]
Example: Header.js: <Navbar /> better to set in a different component.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Are you referring to this file:  `components/layouts/main/header/index.js`

If so, I'm not 100% sure what you are suggesting to do.  Could you give a more specific example?

Btw -- perhaps you could make short video with Loom (https://www.loom.com/) to show me what you have in mind.

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, yes, sorry, I missed a word.
Example: Header.js: <Navbar /> better  to set in a different component.

 I mean one document (Header.jsx) must contain only one component to make less mess code.

**Comment by thecodeclimber** [comment]
Just to further clarify -- are you suggesting that we create two components in two different files `navbar` and `header`?  If so, can you please create new issues and assign them to kirti with instructions of what to do?  Thanks.

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, yes. 
If it just header navbar you can create `./header/Header.jsx` and `./header/HeaderNavbar.jsx`

**Comment by MaksymTaratuta55** [comment]
Created #68
