### ISSUE TITLE
Use css media query instead js

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#48]
Use css media query instead js anywhere it is possible.
Example:
Header.js: "window.addEventListener("resize", resize);" 
Can u use a media query insted?

**Comment by MaksymTaratuta55** [comment]
The same with:
Header.js: handleMobileTabletNavBar()

**Comment by thecodeclimber** [comment]
@kirti75waytech -- Please make the above changes.

@MaksymTaratuta55 -- Would you mind going through the code and finding as many examples as you can of where we can use media queries.  Also, as a side note -- tailwind css have built in class names for media queries:  https://tailwindcss.com/docs/responsive-design

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I found only one place: Header.js

**Comment by thecodeclimber** [comment]
@kirti75waytech -- can you please let me know where we are holding with this.

**Comment by kirti75waytech** [comment]
@thecodeclimber I was working on other issues. But now I have started working on this.

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 @thecodeclimber I have removed js functionality such as ` "window.addEventListener("resize", resize);"` & `handleMobileTabletNavBar()` etc. I have also created the PR #74 for this issue. Please review it and let me know If any other changes are required.
Thanks

**Comment by thecodeclimber** [comment]
@kirti75waytech 
@MaksymTaratuta55 

I am wondering about the closing of these types of issues.  I see that we have created PR #74 which has been successfully merged.  However, this issue still remains open.  What is the best procedure for dealing with BOTH the issue and the PR?  I would assume that once we merge the PR we should also close the issue.  Is that correct?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I think we can create a project with automated kanban desk https://github.com/ramsayinnovations/ramsay-site/projects

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

I think that's a really good idea.  Could you set it up?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, yes, I've created. I hope everything works. We need to test it

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Should we have one project for all issues or should we break it up into mini-projects?  Say a project for everything related to the Contact Form, another project related to General Issues, etc?  What are you thoughts?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I think no, one project is enough for us

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

For me personally, I would like to break this up into sub-projects.  For example, for now I would like two projects:

1. One project for the `develop--clone` branch 
2. Another for everything else.
