### ISSUE TITLE
Rename "Content" folder

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#50]
Please rename "./src/compnents/Content/" to  "./src/compnents/pages/"
Page components put in ./src/components/pages/home/... and etc.

**Comment by thecodeclimber** [comment]
@kirti75waytech -- please rename `.src/components/content` to `./src/components/pages`

NOTE:

* Please make sure to update any relevant imports

**Comment by kirti75waytech** [comment]
@thecodeclimber Changes have been done. Please review this and let me know If changes are required. Thanks
