### ISSUE TITLE
Curves and other similar components should be separated and reusable

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#51]
Contact us: TopCurve, BottomCurve and etc. should be common components or in their own files and reuse.

**Comment by thecodeclimber** [comment]
@kirti75waytech -- please take care of the above.  Please ask @MaksymTaratuta55 if there is a preference for a "common component' or being put in "their own file for reuse".

**Comment by thecodeclimber** [comment]
@kirti75waytech -- what is the status of this?

**Comment by kirti75waytech** [comment]
@thecodeclimber I believe we have a code dependency on the PRs we have created as all of them aren't merged, especially PR #72. If it is possible that the PRs get merged soon. Then, I can start working on this issue from Monday.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 
@kirti75waytech 

Now that i have merged PR #72, can you please advice how to proceed with this? Thanks :).

**Comment by kirti75waytech** [comment]
@thecodeclimber I see the changes have already been done in the develop branch regarding this issue. Please check it and let me know, what other modifications are needed in this issue. 
Thanks

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, @kirti75waytech, I've created these components here. To use them you just need to import and add classes for styling. So I think we can close it.
<img width="304" alt="Screenshot 2020-12-28 at 10 39 11" src="https://user-images.githubusercontent.com/29330551/103201601-ee2dcb80-48f8-11eb-9c96-4cd5fe61bef3.png">

**Comment by thecodeclimber** [comment]
Well done -- thanks.
