### ISSUE TITLE
Create own component for input with error

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#52]
Create own component for input with error and reuse it whole the project

**Comment by thecodeclimber** [comment]
@kirti75waytech -- please take care of the above.  thanks.

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 should I also use react-hook-form for this issue? As the similar discussion was going on in issue: #55

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, no, you should make a component with UI but without logic. It should receive needed props and that's all

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 @thecodeclimber I have resolved this story. Please review it. PR for this issue is #70.
Please let me know If any changes are required. Thanks

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 
@kirti75waytech 

Can we close this issue -- as it seems to have evolved into PR #60

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I think yes and we should reject the PR for it

**Comment by kirti75waytech** [comment]
@thecodeclimber Yes I agree with @MaksymTaratuta55
