### ISSUE TITLE
Add source map to the project

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#53]

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 -- I believe source maps are included by default during development with next.js:  https://nextjs.org/docs/advanced-features/source-maps

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, yes it is. My fault. We can close this issue

**Comment by thecodeclimber** [comment]
Okay - thanks.
