### ISSUE TITLE
Use: useCallback, useMemo for optimization

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#54]

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 -- can you give specific examples of where we should do this.  Thanks.

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber for example
**call-to-action/index.js**
```
const handleFormData = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };
```
Should be
```
const handleFormData = useCallback((e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  }, []);
```

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 -- before we do this, should we not first set up `react-hook-form` and then see if this is even relevant?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, yes, in this component. But if we have such cases in other components, they should be improved

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

can i close this issue?  Is there something left to be done?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I think yes
