### ISSUE TITLE
Separate component logic and layout render

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#55]
Example:
Component with Logic:
**./EmailForm.jsx**
```
import EmailFromLayout from './EmailFromLayout.jsx'

const EmailForm = (props) => {
   const validate = () => ....;
   const submit = () => ....;
   const reset = () => .....;
 
   return <EmailFromLayout validate={validate} submit={submit} reset={reset}
}
```
Component with Layout:
**./EmailFormLayout.jsx**
```
const EmailFormLayout = (props) => { 
   return (
      <Form onSubmit={props.submit}>
           <label /> 
           <input />
           <button onClick={props.reset}>Reset</button>
     </Form>
);
}
```

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 -- can you give specific examples of where we should do this?  Again -- thanks :).

**Comment by MaksymTaratuta55** [comment]
For example ..../contact-us/index.js:
ContactUs component have functions "submitForm", "checkValidations", "handleFormData" and then a long render. I suggest to leave logic (functions) in this component and create new in the current folder "ContactUsLayout.jsx" only with render:
```
const ContactUsLayout = (props) => (
       <div
      id={SECTION_IDS.CONTACT_US}
      className="relative font-sans overflow-hidden -bottom-05 xl:-bottom-05">
      <TopSection />
      <div className="relative pb-8 2sm:pb-16 md:pb-20">
        {!isSuccessFullySubmit &&
          <div>
            <div className="text-center mx-auto">
              <div className="text-grey-800 text-lg md:text-4xl font-extrabold xl:pb-2">
                Get in Touch
              </div>
....
....
....
....
</div
);
```
And then "..../contact-us/index.js" -> "..../contact-us/ContactUs.jsx" and import layout:
const ContactUs = () => {
     const submitForm = () => {....} 
     const checkValidations = () => {....} 
     const handleFormData = () => {....} 

    return <ContactUsLayout submitForm={submitForm} checkValidations={checkValidations}  handleFormData={handleFormData} />

```

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 -- similar question -- should we set up `react-hook-form` first?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, yes we can set up react-hook-form first

**Comment by thecodeclimber** [comment]
@kirti75waytech 
@MaksymTaratuta55 

What is the statis of this now that we are using `react-hook-form`?  Should we close it?  Is there something left to do on this issue?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, yes, it's done
