### ISSUE TITLE
Fixing home folder inside of components

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#56]
@kirti75waytech 

Please take a look at the following video:  https://www.loom.com/share/9f224f318f284feea59f675943c7583f

Here is how the folder and file structure should look:

- components
  - content
    - home
      - AboutUs.jsx
      - CallToAction.jsx
      - Hero.jsx
      - ... 
      
 Thanks

**Comment by thecodeclimber** [comment]
@kirti75waytech 

One more change -- in the video I said that you should keep the `index.js` file named `index.js`.  That was a mistake.  Please change the file name to `Home.jsx` [note the file extension change].

Thanks.

**Comment by thecodeclimber** [comment]
@kirti75waytech As you can see, I have created a number of issues involving updating the names of folders and files.  Please create a unique branch to handle all of these name changes.  Please consult with @MaksymTaratuta55 as to the best way to create this branch.  I.e., naming convention and whether it branches off of the `main` branch or the newly created `development` branch.

Thanks.

**Comment by kirti75waytech** [comment]
@thecodeclimber Changes have been done. And this is resolved under "40-refactoring-folder-structure" this branch. 
Please review this and let me know If any changes are required. 
Thanks
