### ISSUE TITLE
Fix file names in contact-us folder

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#57]
@kirti75waytech 

Please change the file `index.js` to `ContactUs.jsx` in the `components/content/contact-us` folder.

**Comment by thecodeclimber** [comment]
NOTE:

* extension is changed to `.jsx`
* make sure to change any instances where `contact-us/index.js` is being imported.

**Comment by kirti75waytech** [comment]
@thecodeclimber Changes have been done. Please review this and let me know If any changes are required. 
Thanks
