### ISSUE TITLE
Change filename of button.js

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#58]
Please change the filename of `button.js` to `Button.jsx` in `components/elements`

NOTE:

* extension is changed to `.jsx`
* make sure to change any instances where `button.js` is being imported.

**Comment by kirti75waytech** [comment]
@thecodeclimber I have removed this file as It was not in use.

**Comment by thecodeclimber** [comment]
@kirti75waytech -- yeah, i should have deleted this issue.  Thanks.
