### ISSUE TITLE
Fix folder and files in main layout folder

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#59]
Please watch the following video:  https://www.loom.com/share/48c38d3390654278819df3d541c7b6c8

Folder to update:  `components/layouts/main`
New structure:

- components
  - layouts
    - main
      - Footer.jsx
      - Header.jsx
      - MainLayout.jsx

NOTE;

* file extension is changed to `.jsx`
* make sure to update relevant import statements throughout the site

**Comment by kirti75waytech** [comment]
@thecodeclimber Changes have been done. Please review this and let me know If any changes are required. 
Thanks
