### ISSUE TITLE
Form Solution

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#60]
@MaksymTaratuta55 

I would like to use `react-hook-form` to handle our forms:  [https://react-hook-form.com/](https://react-hook-form.com/).  

We also need to connect the form to our ActiveCampaign account.  I actually did so in a previous version of this site using chakra-ui.  Here is a gist of that code:  https://gist.github.com/thecodeclimber/1260636549f49b050215778f81da69de

I would like to rework that code to fit in with tailwind css.  Can you please help with that?

Thanks.

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, yes I can. Can I start?

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 -- yes.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 -- note, I have added the `Not Started` label.  Please change to `In Progress` when you get started.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

can i close this issue?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, yes
