### ISSUE TITLE
Constatns in components mistake

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#61]
**/call-to-action/index.js**
```
const CallToAction = () => {
  const initialState = {
    firstName: "",
    lastName: "",
    company: "",
    email: "",
    isValidate: "",
    isSuccessFullySubmit: false,
  };

  const [state, handleSubmit] = useForm("getInTouch");
  const [formData, setFormData] = useState(initialState);
```
`initialState` should be initialized out of the component (in CallToAction.constants.js) or in `useState({....})`

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 -- again, I am wondering if we should not first get `react-hook-form` set up and then see if these issues still exist.  Your thoughts?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, yes we can set up react-hook-form first

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

can we now close this issue?  is there something else to do with it?

**Comment by MaksymTaratuta55** [comment]
@MaksymTaratuta55, yes, from my side
