### ISSUE TITLE
Separate contact form logic

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#62]
Please create separated components for "input form", "successful result" and "error response". And create a wrapper component that will receive all props and render the needed component

**Comment by thecodeclimber** [comment]
@kirti75waytech -- please implement this.  Thanks.

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 @thecodeclimber I have Created a common ThankYouPage & ErrorResponsePage for `call-to-action` and `contact-us`. While separate FormLayouts I have created under their respective folders. I have created the PR #75 for this issue. Please review it and let me know if further modifications are needed.
Thanks

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, sorry but I've already fixed it in #72. I thought you saw it when reviewing the PR

**Comment by kirti75waytech** [comment]
> @kirti75waytech, sorry but I've already fixed it in #72. I thought you saw it when reviewing the PR

Hi @MaksymTaratuta55 Sorry, I completed this issue before reviewing your PR. So, what should we do now?

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, I prefer to leave my solution. Could you please check my code and UI? Does it work correctly? Or have you some comments?

**Comment by kirti75waytech** [comment]
> @kirti75waytech, I prefer to leave my solution. Could you please check my code and UI? Does it work correctly? Or have you some comments?

@MaksymTaratuta55 I have tested the UI, and below mentioned points I have observed. 
1. When I submitted the empty form, the website started reloading. 
2. Error messages only opened for the selected field when I hit on the respective field.
3. Asterisk is not present in the current UI. Please refer Figma designs.
4. For the ContactUs page, No error fields displayed. Please refer Figma designs for this too.

My suggestions:
1. We shouldn't allow user to submit empty form.
2. In my opinion It could be better if we show error message if the user hit submit button when the form is invalid.
3. and also if a user starts filling the valid info, we can hide the error message instantly.

@thecodeclimber Please review this. What are your thoughts on this?

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, thank you. Could you please create a ticket and assign it to me?

**Comment by kirti75waytech** [comment]
> @kirti75waytech, thank you. Could you please create a ticket and assign it to me?

@MaksymTaratuta55 I have created issue #83 for this. But I would like to know the @thecodeclimber thoughts on this, before we proceed.

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, thx
