### ISSUE TITLE
Change Name of Contact-Us Folder

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#64]
Please change the name of `src/pages/contact-us` to `src/pages/contact`

Thanks.

**Comment by thecodeclimber** [comment]
@kirti75waytech -- also, please change the `index.js` file within the `contact-us` folder to `Contact.jsx`.

All in all, this should be the path: `src/pages/contact/Contact.jsx`

**Comment by kirti75waytech** [comment]
@thecodeclimber  Noted this.

**Comment by kirti75waytech** [comment]
@thecodeclimber  and @MaksymTaratuta55 I have updated the changes which were required, and created the MR #67. 
Kindly review it and let me know If any changes are required.
Thanks
