### ISSUE TITLE
Using Labels

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#65]
Hi there,

I would like to start using labels inside of github issues as follows:

# Three types of issues:

* work
* bugs
* questions & answers

## Work Labels

* Not Started
* In Progress
* Waiting
* Review
* Done

### Explanation

* `Not Started` -- all new issues start off with the `Not Started` label.
* `In Progress` -- once we begin working on an issue we change the label from `Not Started` to `In Progress`
* `Waiting` -- if we need someone else's input or advice we switch the label to `Waiting`
* `Review` -- If we have finished an issue and need approval we switch the label to `Review`
* `Done` -- when an issue has been reviewed and is finished we switch the label to `Done`

**Note:** Once an issue is labeled as `Done` we can close the issue.

## Bug Lables

* Bug
* Fixed

### Explanation

* `Bug` -- for identifying bugs that need to be addressed.  We can then create a new issue or multiple new issues once we have analyzed the bug.  
* `Fixed` -- when a bug is fixed, we change it's label to `Fixed`

**Note:** Once an issue is labeled as `Fixed` we can close the issue.

## Question & Answer Labels

* Question
* Answer
* Explain
* Satisifed

### Explanation

* `Question` -- for questions and clarifications.  All questions start off with the `Question` label.  
* `Answer` -- when a question is answered, the label is switched to `Answer`.  
* `Explain` -- if we are not happy with an answer we switch the label to `Explain`
* `Satisified` -- if we are happy with the answer we switch the label to `Satisfied`.  

**Note:** Once an issue is labeled as `Satisfied` we can close the issue.

---

Please let me know if you would like to make any changes to this system.  Thanks.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 & @kirti75waytech -- please take a look at the above issue.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 & @kirti75waytech -- please note, sometimes when we change a label we will also need to reassign the issue.  For example, when changing a label to `Review` we will have to also assign the issue to whoever it is that does the review.

**Comment by kirti75waytech** [comment]
@thecodeclimber It looks good to me. No changes are required from my side.

**Comment by thecodeclimber** [comment]
@kirti75waytech 

My guess is that we would just add the `question` label while keeping the `in progress` label.  We would then remove the `question` label when the advice has been given.  In terms of who we are asking the advice -- I would referencing them with the `@` in the comment field (rather then assign it to them).

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 
@kirti75waytech 

If we all agree on this labeling system, should we add it to the Wiki section for future reference?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I think we can add it to the wiki https://github.com/ramsayinnovations/ramsay-site/wiki
Also, I think we can remove "Explain", "Satisified" and just use again "question" if need some more clarification or just remove "answer" and "question" if the answer is fine

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

I agree about `explain` and `satisfied`.  We'll just have `question` and `answered`.  We can then close anything labeled as `answered`.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

I agree about removing `explain` and am fine with removing `satisfied`.  My question is how do we single that a question has been properly answered and can be closed?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I think if it is:
1) a question in a task:
 Answer -> remove label 'question -> add label 'answer' -> answer correct? ->
      -> yes -> the one who asked remove label ' answer' -> continue working
      -> no -> the one who asked remove label ' answer' -> ask again -> add label 'question'
2) just question issue (without task):
Answer -> remove label 'question -> add label 'answer' -> answer correct? ->
      -> yes -> the one who asked remove label ' answer' -> close issue
      -> no -> the one who asked remove label ' answer' -> ask again -> add label 'question'

**Comment by thecodeclimber** [comment]
Makes sense -- thanks.

**Comment by thecodeclimber** [comment]
Note: I have updated the Wiki with how to deal with `question` and `answer` labels.
