### ISSUE TITLE
Clean Header component

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#68]
Please separate Navbar and Header components.
`./header/Header.jsx`
`./header/HeaderNavbar.jsx` (if navbar doesn't use in other components)

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 I have cleaned the header component, and created two different files Header.js and HeaderNavBar.js.
Please review it and let me know if any changes are required.
Thanks

**Comment by MaksymTaratuta55** [comment]
@kirti75waytech, I see when you assigned me to review PR, so could you please don't assign me on issues, in this case, it makes me harder to search for issues I need 🙂
