### ISSUE TITLE
Next Link versus Next Router

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#76]
@kirti75waytech 
@MaksymTaratuta55 

I am wondering, why are we using `next/router` for the logo rather then `next/link`?  `next/router` is used more for dynamic links whereas `next/link` is used more for static pages -- as explained nicely in this video:  https://www.youtube.com/watch?v=ERUHYh_65F4

I.e., wouldn't this be better:

```
<Link>
 <a>
   <img src="/img/main-logo.svg" alt="Logo" className="object-contain cursor-pointer w-32 px-2 sm:w-40 lg:w-auto md:px-0 hidden md:block" />
  </a>
</Link>
```

Currntly, this is what we have:

```
<img src="/img/main-logo.svg" alt="Logo" onClick={() => router.push('/')} className="object-contain cursor-pointer w-32 px-2 sm:w-40 lg:w-auto md:px-0 hidden md:block" />
```

Your thoughts?

**Comment by thecodeclimber** [comment]
@kirti75waytech 
@MaksymTaratuta55 

Note, in general I think we should use `next/link` for all static page links and `next/router` for dynamic pages.  Your thoughts?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, yes, you are right. I was going to create a ticket about it today

**Comment by thecodeclimber** [comment]
Great - thanks.

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

Is this issue still relevant or can we close it?

**Comment by MaksymTaratuta55** [comment]
It seems there are some places to fix it. I'll fix them today

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 -- great, thanks.
