### ISSUE TITLE
Google tag manager

### ISSUE THREAD

**Issue by MaksymTaratuta55** [ramsayinnovations/ramsay-site#77]
Here is the code for Google Tag Manager

Paste this code as high in the `<head>` of the page as possible:  
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WHC2X7W');</script>
<!-- End Google Tag Manager -->
```

Additionally, paste this code immediately after the opening `<body>` tag: 
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM_ID_NUMBER"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 
@kirti75waytech 

Before we insert this code, we need to determine the best way to implement Google Tag Manager on a Next.Js site.  I will try and look into this later today and give some further direction.

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, I think I found out the resolution.
![Uploading Screenshot 2020-12-28 at 16.01.30.png…]()
![Uploading Screenshot 2020-12-28 at 16.01.57.png…]()

**Comment by MaksymTaratuta55** [comment]
Something went wrong with images.
<img width="523" alt="Screenshot 2020-12-28 at 16 01 30" src="https://user-images.githubusercontent.com/29330551/103219485-87bfa200-4926-11eb-8377-48c055c554f2.png">

<img width="519" alt="Screenshot 2020-12-28 at 16 01 57" src="https://user-images.githubusercontent.com/29330551/103219495-8e4e1980-4926-11eb-889f-dc1776e74f9d.png">

**Comment by thecodeclimber** [comment]
@MaksymTaratuta55 

I'm not sure if you saw this comment in the PR, so I am reposting it here:

I think we have to modify this further. Here is the official next.js example: https://github.com/vercel/next.js/tree/canary/examples/with-google-tag-manager

They do it differently -- and I think we should follow their lead. I did a little research and there can be an issue with Google Tag Manager loading only once on the initial page load. My guess is that the way they do it solves that problem.

Notice, in particular the following pages on that example:

.env.local.example
pages/_document.js
pages/_app.js
lib/gtm.js
components/GoogleTagManager.js
I think that is all the relevant pages.
