### ISSUE TITLE
Call to Action and Contact Us Page Error Handling

### ISSUE THREAD

**Issue by kirti75waytech** [ramsayinnovations/ramsay-site#83]
@MaksymTaratuta55 @thecodeclimber I have tested the current UI in the `develop` branch, and below mentioned points I have observed.

1. When I submitted the empty form, the website started reloading.
2. Error messages only opened for the selected field when I hit on the respective field.
3. Asterisk is not present in the current UI. As per the Figma designs.
4. For the ContactUs page, No error fields displayed. As per the Figma designs.

My suggestions:
1. We shouldn't allow user to submit empty form.
2. In my opinion It could be better if we show error message if the user hit submit button when the form is invalid.
3. and also if a user starts filling the valid info, we can hide the error message concurrently.

@thecodeclimber Please review this. What are your thoughts on this?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, can I start with it?
