### ISSUE TITLE
Not Every Issue Branch Starts with the Word "Issue"

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#89]
@MaksymTaratuta55 
@kirti75waytech 

I notice that many of the branches start with a number:

![image](https://user-images.githubusercontent.com/65869221/103239363-efd9ac80-4955-11eb-8e10-15644a90f7b2.png)

I personally like the idea of starting a branch with either `issue` or `feature` as we discussed before and would like to go back to doing it that way.  I am wondering, though, is there a particular reason why these branches are starting with a number?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, ok, I'll name new branches with labels

**Comment by thecodeclimber** [comment]
Thanks
