### ISSUE TITLE
NODE_OPTIONS in Package.Json Scripts

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#90]
@kirti75waytech 
@MaksymTaratuta55 

This is a screenshot of the `package.json` file in the `develop` branch:

![image](https://user-images.githubusercontent.com/65869221/103240345-c53d2300-4958-11eb-8d21-2bcd4f251095.png)

I don't understand the `dev` script:

```
  "scripts": {
    "dev": "NODE_OPTIONS='--inspect' next dev",
    "build": "next build",
    "start": "next start",
    "formspree": "formspree deploy"
  },
```

What is `NODE_OPTIONS='--INSPECT'` for?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, it is for debugging https://nodejs.org/en/docs/guides/debugging-getting-started/

**Comment by thecodeclimber** [comment]
okay.  However, it seems to be causing problems for me:

```
λ npm run dev

> frontend@0.1.0 dev C:\laragon\www\projects\ramsay\ramsay-site\ramsay-site
> NODE_OPTIONS='--inspect' next dev

'NODE_OPTIONS' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 dev: `NODE_OPTIONS='--inspect' next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Moshe\AppData\Roaming\npm-cache\_logs\2020-12-29T10_31_31_001Z-debug.log     
```

I am running node version 12.16.3 and npm version 6.14.4.

If I remove that line then next starts up just fine.

Any ideas what the issue is?

**Comment by thecodeclimber** [comment]
Can you please take a look at this question and advice on how to proceed:

> okay. However, it seems to be causing problems for me:
> 
> ```
> λ npm run dev
> 
> > frontend@0.1.0 dev C:\laragon\www\projects\ramsay\ramsay-site\ramsay-site
> > NODE_OPTIONS='--inspect' next dev
> 
> 'NODE_OPTIONS' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! frontend@0.1.0 dev: `NODE_OPTIONS='--inspect' next dev`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the frontend@0.1.0 dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Moshe\AppData\Roaming\npm-cache\_logs\2020-12-29T10_31_31_001Z-debug.log     
> ```
> 
> I am running node version 12.16.3 and npm version 6.14.4.
> 
> If I remove that line then next starts up just fine.
> 
> Any ideas what the issue is?

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, everything is good for me. You can try to use just `--inspect` without `NODE_OPTIONS`. Or you can try to delete package-lock and node_modules and make `npm i`
