### ISSUE TITLE
Perfecting the Develop Branch

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#91]
@kirti75waytech 
@MaksymTaratuta55 

I am going to go through the `develop` branch folder by folder and file by file and note any changes that I think we should make.  I think we need to get the `develop` branch down right and then start to work on these other issues.

Also, I just want to make sure that in the future all `feature` or `issue` branches are created by making a branch of the `develop` branch.  This may be obvious, but I just want to state it here just in case :).

**Comment by thecodeclimber** [comment]
Note, I have created a new label:  `announcement`.

**Comment by kirti75waytech** [comment]
@thecodeclimber Noted the above points.

**Comment by thecodeclimber** [comment]
Great.
