### ISSUE TITLE
tailwind.config.js fixes

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#93]
Please make the following changes to the `tailwind.config.js` file in the  `develop--clone` branch.

# Delete

Please delete the following sub-sections.  We will use the built-in tailwind css options -- if there is not an exact built-in tailwind css option then we will use the closest option available.

* `theme/screens`
* `theme/container` (including the `padding` section)
* `theme/borderRadius`
* `theme/maxWidth`
* `theme/extend/inset`
* `theme/extend/backgroundImage`
* `theme/extend/lineHeight`
* `theme/extend/opacity`

# Changes

* `theme/colors/waring`:  `waring` should be `warning`.
* `theme/fontSize`: remove `2base` (replace all uses with `lg` instead -- it is the same size)
* `theme/exend/lineHeight` rename:
  * 100: "1rem",
  * 200: "2rem",
  * 

# Questions

* Why do we need `zIndex` -10?  Why isn't 0 sufficient (which is part of the tailwind-css default: https://tailwindcss.com/docs/z-index)

**Comment by kirti75waytech** [comment]
> # Questions
> * Why do we need `zIndex` -10?  Why isn't 0 sufficient (which is part of the tailwind-css default: https://tailwindcss.com/docs/z-index)

@thecodeclimber We had a use of zIndex -10 in the Hero section because there we had lots of images and need to handle them with zIndex. But then we changed our design. Now it is not needed, I can delete it from here.

**Comment by kirti75waytech** [comment]
> # Delete
> Please delete the following sub-sections. We will use the built-in tailwind css options -- if there is not an exact built-in tailwind css option then we will use the closest option available.
> 
> * `theme/screens`
> * `theme/container` (including the `padding` section)
> * `theme/borderRadius`
> * `theme/maxWidth`
> * `theme/extend/inset`
> * `theme/extend/backgroundImage`
> * `theme/extend/lineHeight`
> * `theme/extend/opacity`

@thecodeclimber It will create complications if we delete all of them. Some of the custom properties we would require to handle curve images, especially :
> * `theme/extend/inset`
> * `theme/screens`

Please let me know your suggestions on this. Thanks

**Comment by kirti75waytech** [comment]
@thecodeclimber Do I need to create an issue branch for this and then create PR of this branch which could merge to `develop--clone` branch? 
Or Do I need to do the changes in the `develop--clone` branch and push it to `develop--clone` branch after resolving this issue?

**Comment by thecodeclimber** [comment]
@kirti75waytech 

> @thecodeclimber It will create more complications if we delete all of them. Some of the custom properties we would require to handle curve images, especially :
> 
> > * `theme/extend/inset`
> > * `theme/screens`
> 
> Please let me know your suggestions on this. Thanks

For now please delete them.  We will be making other major changes and will deal with any complications that come up after we have made all of the changes.


> @thecodeclimber Do I need to create an issue branch for this and then create PR of this branch which could merge to `develop--clone` branch?
> Or Do I need to do the changes in the `develop--clone` branch and push it to `develop--clone` branch after resolving this issue?

I think for now you can do the changes in the `develop--clone` branch and push them there.  If need be, I'll create another issue to deal with any future changes that need to be made.

**Comment by thecodeclimber** [comment]
@kirti75waytech 

We need to update `theme/fontFamily` in `tailwind.config.js` file.

1. Delete poppins
2. Change the code as follows

```
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  theme: {
    extend: {
      fontFamily: {
        sans: ['Open Sans', ...defaultTheme.fontFamily.sans],
      },
    },
  },
  // ...
}
```

3. Update any occurrences of `font-poppins` anywhere in the `develop--clone` branch to `font-sans`.

**Comment by kirti75waytech** [comment]
@thecodeclimber noted the above points. I will update them in the `develop--clone` branch.

**Comment by thecodeclimber** [comment]
Great -- thanks.

**Comment by kirti75waytech** [comment]
@thecodeclimber @MaksymTaratuta55  I have created a PR #120  for this issue. Kindly review and let me know if any modification is needed in this issue. Thanks
