### ISSUE TITLE
package.json fixes

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#95]
Please make the following changes to the `package.json` file in the `develop--clone` branch.

# Scripts

* Fix `dev`:  it should simply be `next dev`
* Remove `formspree`

# Dependencies

* uninstall `next-optimized-images`
* uninstall `postcss-flexbugs-fixes`

**Comment by kirti75waytech** [comment]
@thecodeclimber I have updated the all the above changes. But I didn't find `dex` in my code. I have created PR #121 for this issue. Please review it and let me know if any other modification we needed in this issue.
Thanks

**Comment by thecodeclimber** [comment]
@kirti75waytech 

`dex` was a typo.  I meant to type `dev`.  With that said, let's leave it for now as we may want to keep it as it is.  I will open up another issue if we need to change it.
