### ISSUE TITLE
remove formspree.json from develop--clone branch

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#96]
Please remove the `formspree.json` file from the `develop--clone` branch.

I am referring to this file: https://github.com/ramsayinnovations/ramsay-site/blob/develop/formspree.json

**Comment by kirti75waytech** [comment]
@thecodeclimber @MaksymTaratuta55 I have resolved this issue. I didn't create any new branch for this issue because there were nothing to compare in the `develop--clone` branch. Hence PR can't be created for this. Instead I pushed the code on `develop--clone` branch.

**Comment by thecodeclimber** [comment]
@kirti75waytech 

okay - thanks.
