### ISSUE TITLE
Advice on the .vscode folder

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#97]
@kirti75waytech 
@MaksymTaratuta55 

Currently we have a `.vscode` folder in the repository.  

Do we need this folder?  

If yes, how should we use it?
If not, we should delete it & add it to the `.gitignore` file in the `develop--clone` branch.

**Comment by MaksymTaratuta55** [comment]
@thecodeclimber, no, I'll do it
