### ISSUE TITLE
Create Universal Curve Component

### ISSUE THREAD

**Issue by thecodeclimber** [ramsayinnovations/ramsay-site#99]
Please create a singluar curve component in the `develop--clone` branch to replace the following components:

* BottomCurve
* FooterCurve
* MobileLowerCurve
* TopCurve

This component would accept props to indicate color, direction, etc.  Here are the relevant differences between different uses of the component:

* SVG Path
* Top or Bottom
* Inverted or Not
* Height
* Width
* Fill Color

Height (and perhaps also width) should very for at different break points.  SVG Path should very depending on whether it is a top curve or bottom curve and whether or not it is inverted.  There are a few minor css changes that also depend on whether it is a top or bottom curve and whether or not it is inverted.  

You can take a look at this online shape divider generator to see how simple it is to create variations:  https://www.shapedivider.app/

We should be able to create a single `Curve` component that can handle these differenes based on props.  Perhaps we could also create a single svg file which responds to those props (i.e., updated path).  Please discuss with @MaksymTaratuta55 on how to best create this component.

**Comment by kirti75waytech** [comment]
@thecodeclimber I will create common file for this, as you have suggested. But @MaksymTaratuta55 if we use .svg file. I observed that at some breakpoints, position of the .svg looks improper as we have only few screen breakpoints. I would like to know your suggestions on this, Please. How can we handle such improperness of the .svg file?
Thanks

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 I would also like to put this statement into your consideration, that we were handling this improperness of the .svg file by using positions along with custom screen breakpoints in tailwind.config.js file. But Now I have removed those breakpoints in issue #93. We aren't able to handle them with this. So, we have to use another approach for this.

**Comment by thecodeclimber** [comment]
@kirti75waytech 

For now, let's not worry about the placement of svg files on smaller screen sizes.  We will deal with that later on.  For now, I just want to create the universal cruve component.

Thanks.

**Comment by kirti75waytech** [comment]
> @kirti75waytech
> 
> For now, let's not worry about the placement of svg files on smaller screen sizes. We will deal with that later on. For now, I just want to create the universal cruve component.
> 
> Thanks.

@thecodeclimber Okay, I will update the required changes and create a common file here.

**Comment by kirti75waytech** [comment]
@MaksymTaratuta55 @thecodeclimber I have resolved this issue and created its PR #131. Please review it and let me know if any modifications are required.
Thanks

**Comment by kirti75waytech** [comment]
@thecodeclimber I have resolved the conflicts for the PR #131. Please review it.
